# Generated by Django 4.1.6 on 2023-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pic",
                    models.URLField(
                        max_length=250, unique=True, verbose_name="Pic_link"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        max_length=250, unique=True, verbose_name="Article_link"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, unique=True, verbose_name="Title"),
                ),
                ("date", models.DateTimeField(verbose_name="Posting_date")),
            ],
        ),
    ]
